### ISSUE TITLE
Open Source Mycetoma (MycetOS) Meeting 26th Oct 2021

### ISSUE THREAD

**Issue by dmitrij176** [OpenSourceMycetoma/Series-1-Fenarimols#65]
### **Open Source Mycetoma (MycetOS) Meeting**

Meeting Zoom link: https://uni-sydney.zoom.us/j/99281549497 

**Time**: UTC 11:00 - London Noon - Amsterdam 1 PM - Sydney 10 PM - New York 7 AM

**Chair**: UCL

**Minute taker**: USYD

Recording can be found [here](https://youtu.be/-BakGS_y6qQ)

Minutes can found here: 
[Minutes for Oct 26 Meeting.docx](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/files/7423002/Minutes.for.Oct.26.Meeting.docx)

**Link to previous meeting** #64 

### 1. Outstanding items from previous meeting

- [x] 1.	The SAR performed by Hung and Kymberly will be checked by Matt and Dimitrij - see #51 
- [ ] 2.	Synthesis of compounds and SAR will be added to manuscript #55 
- [x] 3.	The compounds needed for in vivo testing based on the SAR will be requested from epichem
- [ ] 4.	We should streamline the requests from schools to make series 2 compounds. So far it looks like an ideal project in which schools can participate
- [ ] 5	Series 5 seems so far an ideal series to look further into. Wendy will ask MMV for more details on the compound series with a hit to check if there are more analogues which can be tested in vitro.
- [x] 6      ISNTD update by Matt.
- [x] 7      Shipment of UCL and IMSA compounds to Rotterdam.

### 2. Discussion points for this meeting  

- Erasmus update
- UCL update
- USYD update

### 3. Action Items for November 2021 Meeting

- [x] For this meeting threads, items above, Dmitrij to provide links to relevant pages and other issues where appropriate, for ease of referencing. @dmitrij176 
- [ ] Dmitrij and Hung to agree on common grounds for colour-coding visual summaries (threshold or criteria for green/amber/red/black). We agreed to keep the visual summary concise and free of clutters such as compounds IDs, potency values etc (reserving these for tabulation of data). This conversation should continue at GHI #51
- [x] Hung will investigate the Epichem library and look for compounds that can potentially fill this gap, so we can request Epichem to send those over for testing. @fantasy121 (See below)
- [x] Ma to put the powerpoint of her October update down below for ease of reference @MA-Jjingyi 
- [ ] Manuscript needs urgent updates of Chemistry data (Dmitrij ready, Hung to do) @dmitrij176 @fantasy121 
- [ ] Literature reading is recommended to see if our SAR agree with exisiting SAR somewhere else. (See Keenan’s SAR papers of fenarimol for Chagas, and other papers). Point of interest for lit reading: Azoles vs fungal cytochrome P450 (CYP51 protein) @dmitrij176 @fantasy121 

> Potential starting points (Keenan's papers on Fenarimols vs Chagas, SAR, CYP51 etc.)
> DOI: 10.1021/jm2015809
> DOI: 10.1016/j.bmc.2013.01.050
> DOI: 10.1074/jbc.M113.497990
> DOI: 10.1021/jm401610c

- [x] Kymberley to set up new time for meeting. New time below @kym834 

(One of the discussions points to focus on SAR work and summary for next meeting.)

### 4. Date and time of the next meeting
November 23rd 2021
UTC 10:00 - London 11AM - Rotterdam Noon - Sydney 9 PM - New York 6 AM (Effective till February 2022 Meeting, Daylight saving changes in March meeting, requiring time revision)

**Comment by fantasy121** [comment]
ACTION ITEM 3:
Following our meeting conversation, and discussion Re: SAR summary #51 , I looked through the epichem library again and found some interesting existing compounds that can potentially fill in the current SAR gap, most notably a lack of _meta-_ substitution on the Rings. I double checked that these ones have not been previously biologically evaluated (not tested in [Master List](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=954203120)). What do you think of these @OpenSourceMycetoma/corecontrib ? I think these guys are worth a shot (at least _in vitro_) for the purpose of complementing the current scope of SAR for Motif A
![Post SAR Suggestions Pt1](https://user-images.githubusercontent.com/36176821/139609055-f67551d3-405c-4c1d-8b42-f948ae5ce836.png)

**Comment by wwjvdsande** [comment]
@fantasy121 I'm surely willing to test these in vitro. We can do this in the winter.

**Comment by dmitrij176** [comment]
> ACTION ITEM 3:
> Following our meeting conversation, and discussion Re: SAR summary #51 , I looked through the epichem library again and found some interesting existing compounds that can potentially fill in the current SAR gap, most notably a lack of _meta-_ substitution on the Rings (details in #51 update [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/51#issuecomment-955853549)). I double checked that these ones have not been previously biologically evaluated (not tested in [Master List](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=954203120)). What do you think of these @OpenSourceMycetoma/corecontrib ? I think these guys are worth a shot (at least _in vitro_) for the purpose of complementing the current scope of SAR for Motif A
> ![Post SAR Suggestions Pt1](https://user-images.githubusercontent.com/36176821/139612119-17a3c2b2-7316-48f1-a630-f72c54d3c592.png)

@fantasy121 would these have to be synthesised or they are available from Epichem (upon request)?

**Comment by Wilson-Lm** [comment]
#55 This is the issue for the manuscript draft.

**Comment by wwjvdsande** [comment]
[mycetOS meeting26102021-MA.pptx](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/files/7547330/mycetOS.meeting26102021-MA.pptx)

**Comment by wwjvdsande** [comment]
@fantasy121 @dmitrij176 @Wilson-Lm @MA-Jjingyi @mattodd I added the IC50 and IC90 values to the mastertable. I also added the last survival data. Unfortunately the season ended before we could test all compounds. The last experiments needed to be discarded because even the healthy control larvae died. We will start this up in spring again.
